export const projectsEn = [
    {
        id:"riddle",
        name: "TSCS-Supplier",
        technologies: 'Android, IOS, Web, Ionic, React-native, Cordova, Capacitor',
        imageUrl: 'assets/images/works/1.jpg',
        androidURL: 'https://play.google.com/store/apps/details?id=com.toyota.lios&hl=en_US',
        iosUrl: 'https://apps.apple.com/us/app/shipping-confirmation-system/id1410254004',
        url:'https://www.toyota.com/usa/operations/map/tcal',
        detail:"TSCS. Toyota Shipping Confirmation System focuses on improving two areas of the supply chain.",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
    {
        id:"riddle2",
        name: "TSCS-Driver",
        technologies: 'Android, IOS, Web, Ionic, React-native, Cordova, Capacitor',
        imageUrl: 'assets/images/works/1.jpg',
        androidURL: 'https://play.google.com/store/apps/details?id=com.toyota.tscsdriver&hl=en_US',
        iosUrl: 'https://apps.apple.com/us/app/tscs-driver/id1632498502',
        url:'https://www.toyota.com/usa/operations/map/tcal',
        detail:"The TSCS Driver application allows the driver to confirm their shipment pickups and automatically communicate the pickups with Toyota. It also includes a one stop shop for safety that are required to be reviewed before accessing Toyota’s yard.",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
    {
        id:"teamTraveler",
        name: "Bling Cloud",
        technologies: 'Android, IOS, Web',
        imageUrl: 'assets/images/works/1.jpg',
        url: "https://www.bling.cloud/bling-ai",
        androidURL: 'https://play.google.com/store/apps/details?id=com.bling.cloud',
        iosUrl: 'https://apps.apple.com/us/app/bling-phone/id6468987725',
        detail:"Bling lets your team manage their calls, texts, emails, social media and webchat all inside one beautiful application so that you can make better revenue decisions and lower your overhead.",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
    {
        id:"mautic",
        name: "ITC APPS",
        technologies: 'Android, IOS, Web',
        imageUrl: 'assets/images/works/1.jpg',
        url:'https://www.itcportal.com/app/itc-apps.aspx',
        androidURL: '',
        iosUrl: '',
        detail:"ITC Store App, offers a diverse portfolio of ITC FMCG products, ranging from pantry staples and gourmet delicacies to personal care and stationery. The app ensures secure transactions and brings quality to your fingertips. ITC Store, is your go-to platform for a seamless and hassle-free shopping experience.",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
    {
        id:"pokedex",
        name: "Wings AI",
        technologies: 'Android, IOS, Desktop, Web',
        imageUrl: 'assets/images/works/1.jpg',
        url:'https://wingassistant.com/workspace/',
        androidURL: 'https://play.google.com/store/apps/details?id=com.wing.wingbusinessapp&hl=en_IN&gl=US',
        iosUrl: 'https://apps.apple.com/us/app/wing-assistant/id1529424380',
        detail:"Meet Wing, an unlimited assistant for business - Do things that matter, Delegate the rest to Wing.",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
    {
        id:"portfolio",
        name: "The Grammer You Need",
        technologies: 'Full Stack',
        imageUrl: 'assets/images/works/1.jpg',
        url:'https://thegrammaryouneed.com/home',
        androidURL: '',
        iosUrl: '',
        detail:" The Grammar You Need is a series of full-color visual guides to essential academic English grammar.",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
    {
        id:"Github Protfolio",
        name: "Github Protfolio",
        technologies: '',
        imageUrl: 'assets/images/git-images.jpeg',
        url:'https://github.com/iamanandacharya',
        androidURL: '',
        iosUrl: '',
        detail:"Public contribution to open-source projects. View current project work on GitHub.",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
    
];

