export const projectsEn = [
    {
        id:"teamTraveler",
        name: "Bling Cloud",
        technologies: 'Android, IOS, Web',
        imageUrl: 'assets/images/works/1.jpg',
        url: "https://www.bling.cloud/bling-ai",
        detail:"Bling lets your team manage their calls, texts, emails, social media and webchat all inside one beautiful application so that you can make better revenue decisions and lower your overhead.",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
    {
        id:"mautic",
        name: "ITC APPS",
        technologies: 'Android, IOS, Web',
        imageUrl: 'assets/images/works/1.jpg',
        url:'https://www.itcportal.com/app/itc-apps.aspx',
        detail:"<p>ITC Store App, offers a diverse portfolio of ITC FMCG products, ranging from pantry staples and gourmet delicacies to personal care and stationery. The app ensures secure transactions and brings quality to your fingertips. ITC Store, is your go-to platform for a seamless and hassle-free shopping experience.</p>",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
    {
        id:"pokedex",
        name: "Wings Ai",
        technologies: 'Android, IOS, Desktop, Web',
        imageUrl: 'assets/images/works/1.jpg',
        url:'https://wingassistant.com/workspace/',
        detail:"<p>Meet Wing, an unlimited assistant for business - Do things that matter, Delegate the rest to Wing.</p>",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
    {
        id:"portfolio",
        name: "The Grammer You Need",
        technologies: 'Full Stack',
        imageUrl: 'assets/images/works/1.jpg',
        url:'https://thegrammaryouneed.com/home',
        detail:"<p> The Grammar You Need is a series of full-color visual guides to essential academic English grammar.</p>",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
    {
        id:"riddle",
        name: "TSCS",
        technologies: 'Android, IOS, Web',
        imageUrl: 'assets/images/works/1.jpg',
        url:'https://play.google.com/store/apps/details?id=com.toyota.lios&hl=en_US',
        detail:"TSCS. Toyota Shipping Confirmation System focuses on improving two areas of the supply chain.",
        codeSourceUrl:'',
        detailIsDisplayed: false,
    },
];

